#!/bin/bash
#Declaration of States
TRUE=1
FALSE=0
IS_REMOVED=$FALSE
BEFORE_SCRAPE=0
DURING_SCRAPE=1
DURING_TARGET=2
DURING_JOB=3
STATE=$BEFORE_SCRAPE
OPTION=""
PROM_DIR=""
IP1=""
IP2=""
JOB_NAME=""
HELP_MSG="use --help option to get a guide on how to use config_target"
TARGET=""
STATE=$BEFORE_SCRAPE
CONTENT=""
JOB_CONTENT=""
JOB_SPACES=""
NUM_SPACES=0
LIST=""

#Helper functions 
help() {
 echo ""
 echo ""
 curl https://raw.githubusercontent.com/burningknight7/temp/master/config_target_man.txt
}

#######MAIN#######

if [ $# -eq 0 ]; then
	echo "No arguments passed, "$HELP_MSG
	exit
elif [ $# -gt 0 ]; then
	OPTION="$1"
	if [ $1 = "--help" ]; then
		help
		exit
	elif [ $1 = "-a" ]; then
		if [ ! -f "$2" ]; then
			echo "Enter a prometheus.yml file that exists"
			exit
		fi
		if [[ ! $3 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
			echo "Enter a valid ip address"
			exit
		fi
		PROM_DIR="$2"
		IP1="$3"
		TARGET="- targets: ['$IP1:9100','$IP1:7676','$IP1:9256','$IP1:9399','$IP1:9104'"
		if [ $# -eq 4 ] && [[ $4 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
			IP2="$4"
			TARGET=$TARGET",'$IP2:9100','$IP2:9256','$IP2:7676','$IP2:9399','$IP2:9104']"
		else
			TARGET=$TARGET"]"
		fi
		JOB_NAME="ems_$IP1"
	elif [ $1 = "-rm" ]; then
		if [ ! -f "$2" ]; then
			echo "Enter a prometheus.yml file that exists"
			exit
		fi
		PROM_DIR="$2"
		JOB_NAME="$3"
	elif [ $1 = "-l" ]; then
		if [ ! -f "$2" ]; then
			echo "Enter a prometheus.yml file that exists"
			exit
		fi
		PROM_DIR="$2"
	else
		echo "Wrong arguemnt passed, "$HELP_MSG
		exit
	fi
fi	 

while IFS= read -r line
do

if [ $STATE -eq $BEFORE_SCRAPE ]; then
	if [[ $line == *"scrape_configs:"* ]]; then
		STATE=$DURING_SCRAPE
	fi
	CONTENT=$CONTENT$line"\n"
elif [ $STATE -eq $DURING_SCRAPE ]; then
	if [ "$OPTION" = "-a" ]; then
		if [[ $line =~ ^[[:space:]]+-[[:space:]]+[a-zA-Z0-9_]+:.*$ ]]; then
			NUM_SPACES=`expr index "$line" "-"`
			NUM_SPACES=$((NUM_SPACES - 1))
			
			for i in $( seq 1 $NUM_SPACES)
			do
				
				JOB_SPACES=$JOB_SPACES" "
			done
			
			CONTENT=$CONTENT$JOB_SPACES"- job_name: '$JOB_NAME'\n\n"
			CONTENT=$CONTENT$JOB_SPACES"  metrics_path: '/metrics'\n\n"
			CONTENT=$CONTENT$JOB_SPACES"  static_configs:\n"
			CONTENT=$CONTENT$JOB_SPACES"  "$TARGET"\n\n"$line"\n"  
			STATE=$BEFORE_SCRAPE
		else
			CONTENT=$CONTENT$line"\n"
		fi
	elif [ "$OPTION" = "-rm" ]; then
		if [[ $line =~ ^[[:space:]]+-[[:space:]]+[a-zA-Z0-9_]+:.*$ ]]; then
			if [[ $line == *"job_name"* ]] && [[ $line == *"$JOB_NAME"* ]]; then
				IS_REMOVED=$TRUE
			fi
			NUM_SPACES=`expr index "$line" "-"`
			NUM_SPACES=$((NUM_SPACES - 1))
			STATE=$DURING_JOB
			JOB_CONTENT=$JOB_CONTENT$line"\n"
		else
			CONTENT=$CONTENT$line"\n"
		fi
	elif [ "$OPTION" = "-l" ]; then
		if [[ $line =~ ^[[:space:]-]+job_name:[[:space:]]+[\'\"].*[\'\"].*$ ]]; then	
			echo $line
		elif [[ $line =~ ^[[:space:]-]+targets:.*$ ]]; then
			echo $line
			if [[ ! $line == *"]"* ]]; then	
				STATE=$DURING_TARGET
			else
				echo ""
			fi
		fi
	fi
elif [ $STATE -eq $DURING_TARGET ]; then
	if [ $OPTION = "-l" ]; then
		if [[ $line == *"]"* ]]; then
			echo $line
			echo ""
			STATE=$DURING_SCRAPE
		else 
			echo $line
		fi
	fi

elif [ $STATE -eq $DURING_JOB ]; then
	if [ $OPTION = "-rm" ]; then
		LESS_SPACES=$(($NUM_SPACES - 1))
		if [[ $line =~ ^[[:space:]]{0,$LESS_SPACES}[a-zA-Z0-9_-]+:.* ]]; then
			if [ $IS_REMOVED -eq $FALSE ]; then
				CONTENT=$CONTENT$JOB_CONTENT$line"\n"
			else
				CONTENT=$CONTENT$line"\n"
			fi
			STATE=$BEFORE_SCRAPE
		
		else
			if [[ $line =~ ^[[:space:]]{$NUM_SPACES}-.*$  ]]; then
				if [ $IS_REMOVED -eq $FALSE ]; then
					CONTENT=$CONTENT$JOB_CONTENT
				fi
				IS_REMOVED=$FALSE
				if [[ $line == *"job_name:"* ]] && [[ $line == *"$JOB_NAME"* ]]; then
					IS_REMOVED=$TRUE
				fi
				JOB_CONTENT=$line"\n"
			elif [[ $line =~ ^[[:space:]]+job_name:[[:space:]]+[\'\"]$JOB_NAME[\'\"].*$ ]]; then
				IS_REMOVED=$TRUE
				JOB_CONTENT=$JOB_CONTENT$line"\n"
			else 
				JOB_CONTENT=$JOB_CONTENT$line"\n"
			fi
		fi
	fi
			
fi

done < "$PROM_DIR"

if [ $STATE -eq $DURING_JOB ]; then
	if [ "$OPTION" = "-rm" ]; then
		if [ $IS_REMOVED -eq $FALSE ]; then
			CONTENT=$CONTENT$JOB_CONTENT
		fi
	fi
fi

if [ "$OPTION" = "-a" ] || [ "$OPTION" = "-rm" ]; then
	printf "$CONTENT" > "$PROM_DIR"
fi 
