#!/bin/bash
#Declaration of States
BEFORE_SCRAPE=0
DURING_SCRAPE=1
DURING_TARGET=2
STATE=$BEFORE_SCRAPE
OPTION=""
PROM_DIR=""
IP1=""
IP2=""
JOB_NAME=""
HELP_MSG="use --help option to get a guide on how to use config_target"
TARGET=""
STATE=$BEFORE_SCRAPE
CONTENT=""
JOB_CONTENT=""
JOB_SPACES=""
LIST=""
#IFS='%'

#Helper functions 
help() {
 echo "This will print the manual"
}


	



#######MAIN#######

if [ $# -eq 0 ]; then
	echo "No arguments passed, "$HELP_MSG
elif [ $# -gt 0 ]; then
	OPTION="$1"
	if [ $1 = "--help" ]; then
		help
		exit
	elif [ $1 = "-a" ]; then
		if [ ! -f "$2" ]; then
			echo "Enter a prometheus.yml file that exists"
			exit
		fi
		if [[ ! $3 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
			echo "Enter a valid ip address"
			exit
		fi
		PROM_DIR="$2"
		IP1="$3"
		TARGET="- targets: ['$IP1:9100','$IP1:7676','$IP1:9256','$IP1:9399','$IP1:9104'"
		if [ $# -eq 4 ] && [[ $4 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
			IP2="$4"
			TARGET=$TARGET",'$IP2:9100','$IP2:9256','$IP2:7676','$IP2:9399','$IP2:9104']"
		else
			TARGET=$TARGET"]"
		fi
		JOB_NAME="ems_$IP1"
	elif [ $1 = "-rm" ]; then
		if [ ! -f "$2" ]; then
			echo "Enter a prometheus.yml file that exists"
			exit
		fi
		PROM_DIR="$2"
		JOB_NAME="$3"
	elif [ $1 = "-l" ]; then
		if [ ! -f "$2" ]; then
			echo "Enter a prometheus.yml file that exists"
			exit
		fi
		PROM_DIR="$2"
	else
		echo "Wrong arguemnt passed, "$HELP_MSG
		exit
	fi
fi


###Everything is valid, go ahead###	 


#echo $OPTION
#echo $PROM_DIR
#echo $IP1
#echo $IP2
#echo $JOB_NAME
#echo $TARGET

while IFS= read -r line
do

if [ $STATE -eq $BEFORE_SCRAPE ]; then
	if [[ $line == *"scrape_configs:"* ]]; then
		STATE=$DURING_SCRAPE
	fi
	CONTENT=$CONTENT$line"\n"
elif [ $STATE -eq $DURING_SCRAPE ]; then
	if [ "$OPTION" = "-a" ]; then
		if [[ $line =~ ^[[:space:]]+-[[:space:]]+[a-zA-Z0-9_]+:[[:space:]]*[\'\"].*[\'\"].*$ ]]; then
			#JOB_SPACES=`echo $line| awk -F- '{print $1}'`
			NUM_SPACES=`expr index "$line" "-"`
			NUM_SPACES=$((NUM_SPACES - 1))
			echo $NUM_SPACES
			for i in $( seq 1 $NUM_SPACES)
			do
				echo "$i"
				JOB_SPACES=$JOB_SPACES" "
			done
			echo "s"$JOB_SPACES"Here they are"
			CONTENT=$CONTENT$JOB_SPACES"- job_name: '$JOB_NAME'\n\n"
			CONTENT=$CONTENT$JOB_SPACES"  metrics_path: '/metrics'\n\n"
			CONTENT=$CONTENT$JOB_SPACES"  static_configs:\n"
			CONTENT=$CONTENT$JOB_SPACES"  "$TARGET"\n\n"$line"\n"  
			STATE=$BEFORE_SCRAPE
		else
			CONTENT=$CONTENT$line"\n"
		fi
	elif [ "$OPTION" = "-rm" ]; then
		##We'll figure something ou##
		exit
	elif [ "$OPTION" = "-l" ]; then
		#####TODO#####	
		if [[ $line == *"job_name"* ]]; then
			echo $line
		elif [[ $line == *"targets"* ]]; then
			echo $line
			if [[ ! $line == *"]"* ]]; then	
				STATE=$DURING_TARGET
			else
				echo ""
			fi
		fi
	fi
elif [ $STATE -eq $DURING_TARGET ]; then
	if [ $OPTION = "-l" ]; then
		if [[ $line == *"]"* ]]; then
			echo $line
			echo ""
			STATE=$DURING_SCRAPE
		else 
			echo $line
		fi
	fi
fi


done < "$PROM_DIR"


if [ "$OPTION" = "-a" ]; then
	printf "$CONTENT" > "$PROM_DIR"
fi 

#unset IFS 
