#!/bin/bash
count="2"
for i in $( seq 1 $count )
do
	echo "$i"
done
IFS='%'
line="  - job_name: 'example' #dsdsd's"
echo $line
if [[ $line =~ ^[[:space:]]+-[[:space:]]+[a-zA-Z0-9_]+:[[:space:]]*[\'\"].*[\'\"].*$ ]]; then
	echo "Yup matches it"
else
	echo "Does not"
fi
unset IFS
