#!/bin/bash
IFS='%'
NUM_SPACES=2
JOB_NAME="example"
line="  - job_name: 'example' #"
if [[ $line =~ ^[[:space:]]{$NUM_SPACES}-[[:space:]]+job_name:[[:space:]]+[\'\"]$JOB_NAME[\'\"].*$ ]]; then
	echo "Yup Matches It"
else
	echo "Does not"
fi
unset IFS 
